### PR TITLE
Add a simple bounce on page changes

### PR DESCRIPTION
**Pull request by esensar**
This adds a very simple bounce effect on page changes by using `OvershootInterpolator` for animation. This results in faster animation in the beginning, so this may need some tweaking.

### CODE REVIEW

**Comment by tibbi** [comment]
it doesnt move widgets now, they are stuck on 1 screen only

**Comment by esensar** [comment]
I haven't been able to reproduce that issue, but I found an issue that caused widgets to get moved around and their menu to be randomly shown when swiping between pages while tapping in their areas.

**Comment by tibbi** [comment]
this just doesnt work well to me, widgets keep blinking on swipes

**Comment by esensar** [comment]
> this just doesnt work well to me, widgets keep blinking on swipes

Does it happen on `main` branch too? Not sure why these changes would cause it... I can't reproduce it on either of my devices

**Comment by tibbi** [comment]
cant even run the main branch, it keeps crashing even after cleaning the project... does it work for you?

**Comment by esensar** [comment]
> cant even run the main branch, it keeps crashing even after cleaning the project... does it work for you?

It does until I clean the app storage. I think it is related to the addition of folders, since I haven't updated DB version (since there was no release in the meantime).

Weirdly, it happens on clean install too, but I think it happens because `android:allowBackup` is true and I guess my backup has an older version of DB.

**Comment by tibbi** [comment]
fix main branch then please, installing has to work if I clean app data and uninstall it and I also sync gradle and clean project in Android Studio

**Comment by esensar** [comment]
The crash happens due to differences between the folders branch and the main branch (since there were database changes, but version was not updated since there were no releases in between) - this will not affect any of the users, since they did not have any of the versions we had in between - all current users have DB version 4 and migration to DB version 5 will properly handle it.

The reason this happens even on clean install is that `allowBackup` is true for the application, so the "broken" version of the database has been backed up. To confirm this, you can install the app, clear its data and then launch it. It should work then. Afterwards you can go to phone settings and force backup, this will upload the updated version of the database as your backup and this issue should no longer occur on reinstall.

**Comment by tibbi** [comment]
it isnt about the users, I cannot compile and run main branch at all, so cannot test this PR either..

**Comment by esensar** [comment]
Oh, I didn't know the issue was in compile time, I thought the app crashed.

Could you send me the compile error that you get? Since I can't reproduce that, I can successfully build and run the app from both the main branch and this branch.

**Comment by tibbi** [comment]
my bad, bad wording... It is a crash indeed at launching the app, not a compile error.

**Comment by esensar** [comment]
Is it related to the database version? If so, please read my comments above. This is not an issue with the app, just delete app data after installing it and start it. It should work fine then.

**Comment by tibbi** [comment]
ok thanks, seems to be good now

**Pull request merged**
