### PR TITLE
Allow drawing under notches and system bars

### LINKED ISSUE #73: Launcher is not properly working on notch

### PR DESCRIPTION
**Pull request by esensar**
This closes #73

### CODE REVIEW

**Comment by tibbi** [comment]
doesnt work on my Android 11, the top bar is grey

**Comment by esensar** [comment]
I have tested on Android 10 and Android 13. Maybe it is specific to manufacturer? Which device is it?

**Comment by tibbi** [comment]
my old OnePlus 6, but the transparent statusbar works just fine in Nova launcher and other apps.

**Comment by esensar** [comment]
Unfortunately, I can't reproduce it. Can you test the latest changes? If these didn't help, I will try to find a way to reproduce it to fix it properly.

**Comment by tibbi** [comment]
nope, not working :/ Guess Ill have to take a look at it then

**Comment by esensar** [comment]
Hmm, looks like it might be related to that specific version of Android. I managed to reproduce it on emulator.

**Comment by esensar** [comment]
Found the issue.
Updating search bar colors automatically updates status bar. I just made sure to return status bar color to transparent after making these updates.

**Comment by tibbi** [comment]
alright thanks, it works now

**Pull request merged**
