### PR TITLE
Add support for app shortcuts

### LINKED ISSUE #49: Feature Request: Support App Actions
It'd be great if we could tap and hold on apps to bring up their actions.
For example, Simple Dialer allows you to launch to the dial pad directly, FitBit to log different things, Magic Earth to navigate to saved locations, etc.

### PR DESCRIPTION
**Pull request by esensar**
This closes #49

### CODE REVIEW

**Comment by tibbi** [comment]
nice, but you seem to be using some wrong labels. For example Simple Notes should show "New checklist" and "New text note", but it shows "Checklist" and "Text note"

**Comment by tibbi** [comment]
cant seem to test it, Android Studio is messed up and always launches the old versions no matter what I do... Will accept it though and test on master. Shortcuts should be draggable on the home screen though, will add a new issue for it. Thanks

**Comment by tibbi** [comment]
dont you have some caching or building issues? This app behaves so weird to me.

**Comment by esensar** [comment]
I haven't noticed anything weird. What issues did you notice?

**Comment by tibbi** [comment]
nevermind then, should be better now

**Pull request merged**
