### PR TITLE
Fix scrolling on widgets on home screen

### LINKED ISSUE #139: Interacting with movable elements in widgets triggers context menu and moves them
## Description
When interacting with widgets that have scrollable lists (k9 mail list widget, qksms messages widget, simple notes widget, termux shortcuts widget, etc) context menu for resizing and removing the widget gets triggered on any interaction even without long tapping, for example during a quick swipe to scroll the list. Sometimes such interactions also move the widget itself.

## App version
5.1.0

## OS info
LineageOS 20 (android 13)

### PR DESCRIPTION
**Pull request by esensar**
This closes #139

### CODE REVIEW

**Comment by esensar** [comment]
This also closes the issue from the video in #130

**Comment by ClockGen** [comment]
@esensar can you please make another debug build so I could test if everything works as expected?

**Comment by esensar** [comment]
[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12698794/launcher-core-release.apk.zip)

Here is the build. Thank you so much for testing this.

**Comment by ClockGen** [comment]
@esensar I've tested it, all previous bugs are fixed.

However, I had a new bug, widgets "stuck" on my screen and weren't moving when I switched pages. I removed widgets and wasn't able to reproduce it again.

I'll comment if I find a way to reproduce it.

@tibbi can you please tag a new version? The previous build cycle didn't include 5.1.0, so the next one will already pick up the version with recent fixes.

**Comment by esensar** [comment]
I think I fixed that one in #143 . I think you reproduce it by changing grid size. That is how I reproduced it anyways.

Can you check if it happens on this build? (other fixes may not be included in it since it is in a separate branch)

[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12699270/launcher-core-release.apk.zip)

**Comment by tibbi** [comment]
@ClockGen not sure what you mean, 5.1.0 has been tagged properly, F-droid is just usually a couple days behind. I will release a new version soon if everything is ok in the testing one sent above.

**Comment by ClockGen** [comment]
@esensar I can't reproduce it in this version either.

@tibbi I meant that F-Droid still didn't build the previous version, so when it does, it will build both, including the new one, so there's no gap when only the bugged version will be present in F-Droid.

**Comment by ClockGen** [comment]
Hm. I managed to reproduce it. In the latest version, if I move any widget to the lower screen bound and then decrease amount of rows, the widget dissapears, however the space is still "occupied" and I can't drag any icons there or place new widgets. If I then increase the amount of rows back, the widget appears again. 

In older versions this bug reproduces as you described, the widget gets stuck.

Another issue I just found - when I decrease amount of rows to 5 and less, the launcher crashes unconditionally, and keeps crashing on startup, unless app storage is cleaned/app reinstalled. This happens on all versions including release 5.1.0. This happens even with clean app installation with no other changes in it. Doesn't happen if I do the same with amount of columns.

**Comment by esensar** [comment]
> Hm. I managed to reproduce it. In the latest version, if I move any widget to the lower screen bound and then decrease amount of rows, the widget dissapears, however the space is still "occupied" and I can't drag any icons there or place new widgets. If I then increase the amount of rows back, the widget appears again.
> 
> In older versions this bug reproduces as you described, the widget gets stuck.
> 
> Another issue I just found - when I decrease amount of rows to 5 and less, the launcher crashes unconditionally, and keeps crashing on startup, unless app storage is cleaned/app reinstalled. This happens on all versions including release 5.1.0. This happens even with clean app installation with no other changes in it. Doesn't happen if I do the same with amount of columns.

Does it happen right after install with clean storage or are there some special conditions for it (the crash I mean)?

**Comment by ClockGen** [comment]
No, happens right away, just a clean install -> change amount of rows in settings to 5 or 4 and upon leaving the settings it crashes.

**Comment by esensar** [comment]
> No, happens right away, just a clean install -> change amount of rows in settings to 5 or 4 and upon leaving the settings it crashes.

Wow, that one is really weird. I can reproduce it too now. I changed row settings so many times, it never crashed, but with these simple steps it crashes 100% of the time.

**Comment by esensar** [comment]
@ClockGen 
I think I fixed that issue in #144 
I have prepared a build if you want to test it out
[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12699888/launcher-core-release.apk.zip)

**Comment by ClockGen** [comment]
Yes, no longer crashes. The first bug with invisible widgets is still present though.

**Comment by esensar** [comment]
Yeah, not sure what to do about that one. Probably best to just completely remove widget in these cases.

**Comment by ClockGen** [comment]
Seems like a rational choice. Maybe it's also worth to do the same for apps and folders that also go out of grid bounds.

**Comment by esensar** [comment]
I am thinking, these ones will not really break anything, since they occupy just one spot and it might break layouts that somebody has been building for a long time just because they tried a different layout for a second.

That is why I was hoping I can somehow preserve widgets too, but it then introduces too many other issues (like the one we have - if I solved it by letting users drop items there, then there would be overlap on bigger grid sizes...)

**Comment by esensar** [comment]
I think that removing them only if user drops an icon over area that they are supposed to occupy is the least destructive option. Since I assume some people will just try different grid sizes and then go back to their original one, so we probably want to preserve as much of the original layout as possible.

**Comment by esensar** [comment]
I have implemented it as described above in #145

This is the build with that fix if you want to check it out @ClockGen 
[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12700241/launcher-core-release.apk.zip)

**Comment by ClockGen** [comment]
Works as expected, I tried really hard to break it. I can't resize or move other widgets into "invisible" widgets, but I assume it's intended behavior. Placing apps into the space occupied by "invisible" widgets destroys them as expected.

**Comment by esensar** [comment]
Hmm, I actually missed that. We should probably do the same in these situations as well, since we should act as if they don't exist really.

**Comment by esensar** [comment]
I have covered these cases as well. Here is a build if you want to check it out.

[launcher-core-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Launcher/files/12700473/launcher-core-release.apk.zip)

**Comment by ClockGen** [comment]
I tested every situation I could think of, seems to be working fine.

**Comment by tibbi** [comment]
thanks for the help, will start rolling out a new version soon

**Pull request merged**
