### PR TITLE
Check both short and long label for shortcuts

### LINKED ISSUE #132: Sometimes app shortcuts are empty
## Description
Sometimes app shortcuts don't have any text on them

## Screenshots
Screenshot_20230921-100903_Launcher_1

## App version
5.1.0

## OS info
LineageOS 20 (Android 13)

### PR DESCRIPTION
**Pull request by esensar**
This closes #132

### CODE REVIEW

**Comment by tibbi** [comment]
have you managed reproducing it? Does it solve the icon colors too?

**Comment by esensar** [comment]
Yeah, I could reproduce it on Termux and Play Store. Probably some other apps too (the ones that were missing the long label).

**Comment by esensar** [comment]
Not sure about the colors. What is the issue with icon colors?

**Comment by tibbi** [comment]
well on the report screenshot the Settings color seems to be black. But that might be related to label missing, not sure

**Comment by esensar** [comment]
Oh, well these icons use their original colors defined by the app, and in this case I think the app is termux and it has black icons for these shortcuts.

**Comment by tibbi** [comment]
ok, just check how do other popular launchers handle it, if its ok

**Pull request merged**
